---
- name: Configure Docker on test-server Instances
  hosts: all
  become: true
  tasks:
    - name: Updating apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
      become: yes

    - name: Docker Login
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: your_username  # Replace with your Docker Hub username
        password: your_password  # Replace with your Docker Hub password or authentication token
      become: yes

    - name: Run the Bank application
      command: docker run -dt -p 8084:8081 belosheabhijeet/banking-finance-app:1.0
      become: yes
